# Generated by Django 5.1.4 on 2025-03-06 23:01

import Tech.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to='cover_photos/', validators=[Tech.models.validate_image]),
        ),
    ]
