# Generated by Django 5.1.4 on 2025-03-23 03:37

import cloudinary.models
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech', '0002_alter_customuser_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='brands')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Ahorro', 'Ahorro'), ('Corriente', 'Corriente')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='branchesfijos',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='swift_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='logos',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_cover.jpg', max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_profile.jpg', max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('store', 'Tienda')], default='store', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('shipped', 'Enviado'), ('completed', 'Completado'), ('canceled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='barcodes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='qrcodes'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='products/gallery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tech.brand'),
        ),
    ]
